### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by apiccato** [IsaacGluck/Tutee#13]
A bunch of fields used in the register method are not in the form (zipcode, etc.). I commented them out for now, coby if you want edit register form to have those fields, i dunno if you will be able to test your search method

**Comment by CobyGoldbergs** [comment]
Responded in the pull request, but those fields are there. Zipcode/long/lat are accessed through googlemaps using the address, inputed as seen in the attached pic.
![screen shot 2015-01-12 at 7 43 54 488pm](https://cloud.githubusercontent.com/assets/5508527/5714203/6f8f20b8-9a93-11e4-9da6-95ca087a01c8.png)
