### ISSUE TITLE
Gmail Login

### ISSUE THREAD

**Issue by CobyGoldbergs** [IsaacGluck/Tutee#9]
Allow loging in with google, while still requiring them to register the account separately. Would just be helpful to improve speed/ ease of coming back to the site. I'm putting it here as a reminder to myself.

**Comment by IsaacGluck** [comment]
Honestly, I think it would be unwanted from what I see of other of these kinds of websites.

**Comment by CobyGoldbergs** [comment]
What do you mean? I just thought it'd be good for people who register with gmails to have a one click way of logging in, instead of always having to do username/password.
